### ISSUE TITLE
Fails to upgrade Ansible on an already-provisioned host

### ISSUE THREAD

**Issue by ches** [debops/ansible-role-ansible#1]
Hi, thanks for sharing the role!

If you provision a host with one `role_ansible_version` value set, and then attempt to upgrade Ansible by raising this later, it can hang on the `Install Ansible .deb package (new version)` task because the role itself has modified `/etc/ansible/ansible.cfg` and apt will prompt what to do about changes conflicting with the dist version. In a non-interactive Ansible run of course, this prompt hangs indefinitely.

Using the built-in `apt` module with the `deb` parameter to point to a file, instead of a `shell: dpkg -i` action, helps avoid issues like this.

**Comment by cweagans** [comment]
I use this role in production, FWIW. Very useful.

**Comment by drybjed** [comment]
@cweagans Can you tell how do you use it? Does it install Ansible on Ansible Controller host, or do you use it to setup `ansible-pull` command on remote hosts?

**Comment by cweagans** [comment]
I set up Ansible on my Jenkins machine, and then have a nightly build that runs the Ansible playbooks for the rest of the machines that I run.

I suppose ansible-pull might be a bit more straightforward to set up, but I prefer running it this way because it ensures that I can run the playbooks in exactly the same way locally against a few Vagrant VMs.

**Comment by drybjed** [comment]
I'm closing this issue since the role is deprectated. The [`debops.debops`](https://github.com/debops/ansible-debops/) role can be used to build and install Ansible from `git` repository, and it supports upgrades.
